// <auto-generated />
using CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CityInfo.API.Migrations
{
    [DbContext(typeof(CityInfoContext))]
    [Migration("20250423105827_Database")]
    partial class Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The one with that big park.",
                            Name = "New York City"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The one with the cathedral that was never really finished.",
                            Name = "Antwerp"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The one with the big tower.",
                            Name = "Paris"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The one with the clock tower and palace.",
                            Name = "London"
                        },
                        new
                        {
                            Id = 5,
                            Description = "The one with the cherry blossoms and skyscrapers.",
                            Name = "Tokyo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The one with the Colosseum and ancient history.",
                            Name = "Rome"
                        },
                        new
                        {
                            Id = 7,
                            Description = "The one with the famous opera house.",
                            Name = "Sydney"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The one with Gaudi's architecture.",
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 9,
                            Description = "The one with the canals and bicycles.",
                            Name = "Amsterdam"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The one with the Brandenburg Gate and rich history.",
                            Name = "Berlin"
                        },
                        new
                        {
                            Id = 11,
                            Description = "The one with water instead of streets.",
                            Name = "Venice"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The one with the tallest building in the world.",
                            Name = "Dubai"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The one with the Golden Gate Bridge.",
                            Name = "San Francisco"
                        },
                        new
                        {
                            Id = 14,
                            Description = "The one with the Christ the Redeemer statue.",
                            Name = "Rio de Janeiro"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The one with the astronomical clock and castle.",
                            Name = "Prague"
                        },
                        new
                        {
                            Id = 16,
                            Description = "The one that spans two continents.",
                            Name = "Istanbul"
                        },
                        new
                        {
                            Id = 17,
                            Description = "The one with classical music and imperial palaces.",
                            Name = "Vienna"
                        },
                        new
                        {
                            Id = 18,
                            Description = "The one with ornate shrines and vibrant street life.",
                            Name = "Bangkok"
                        },
                        new
                        {
                            Id = 19,
                            Description = "The one that's a city-state with futuristic gardens.",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 20,
                            Description = "The one with the stunning skyline and harbor.",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 21,
                            Description = "The one with K-pop and ancient palaces.",
                            Name = "Seoul"
                        },
                        new
                        {
                            Id = 22,
                            Description = "The one with the Acropolis and ancient ruins.",
                            Name = "Athens"
                        },
                        new
                        {
                            Id = 23,
                            Description = "The one with the pyramids nearby.",
                            Name = "Cairo"
                        },
                        new
                        {
                            Id = 24,
                            Description = "The one with the colorful St. Basil's Cathedral.",
                            Name = "Moscow"
                        },
                        new
                        {
                            Id = 25,
                            Description = "The one with the CN Tower and diverse neighborhoods.",
                            Name = "Toronto"
                        },
                        new
                        {
                            Id = 26,
                            Description = "The one with tango and European architecture.",
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 27,
                            Description = "The one with Table Mountain and beautiful coastlines.",
                            Name = "Cape Town"
                        },
                        new
                        {
                            Id = 28,
                            Description = "The one built on islands with colorful old town.",
                            Name = "Stockholm"
                        },
                        new
                        {
                            Id = 29,
                            Description = "The one with the vibrant markets and red buildings.",
                            Name = "Marrakech"
                        },
                        new
                        {
                            Id = 30,
                            Description = "The one with traditional temples and gardens.",
                            Name = "Kyoto"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "The most visited urban park in the United States.",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "A 102-story skyscraper located in Midtown Manhattan.",
                            Name = "Empire State Building"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "A Gothic style cathedral, conceived by architects Jan and Pieter Appelmans.",
                            Name = "Cathedral of Our Lady"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "The finest example of railway architecture in Belgium.",
                            Name = "Antwerp Central Station"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "A wrought-iron lattice tower on the Champ de Mars.",
                            Name = "Eiffel Tower"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "The world's largest museum.",
                            Name = "The Louvre"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 4,
                            Description = "The famous clock tower at the north end of the Palace of Westminster.",
                            Name = "Big Ben"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 4,
                            Description = "A historic castle on the north bank of the River Thames.",
                            Name = "Tower of London"
                        },
                        new
                        {
                            Id = 9,
                            CityId = 5,
                            Description = "A broadcasting and observation tower, and the tallest structure in Japan.",
                            Name = "Tokyo Skytree"
                        },
                        new
                        {
                            Id = 10,
                            CityId = 5,
                            Description = "One of the busiest pedestrian crossings in the world.",
                            Name = "Shibuya Crossing"
                        },
                        new
                        {
                            Id = 11,
                            CityId = 6,
                            Description = "An oval amphitheatre in the centre of the city.",
                            Name = "Colosseum"
                        },
                        new
                        {
                            Id = 12,
                            CityId = 6,
                            Description = "The smallest independent state in the world.",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 13,
                            CityId = 7,
                            Description = "A multi-venue performing arts centre at Sydney Harbour.",
                            Name = "Sydney Opera House"
                        },
                        new
                        {
                            Id = 14,
                            CityId = 7,
                            Description = "One of Australia's most famous beaches.",
                            Name = "Bondi Beach"
                        },
                        new
                        {
                            Id = 15,
                            CityId = 8,
                            Description = "A large unfinished Roman Catholic church designed by Antoni Gaudí.",
                            Name = "Sagrada Familia"
                        },
                        new
                        {
                            Id = 16,
                            CityId = 8,
                            Description = "A public park system composed of gardens and architectural elements.",
                            Name = "Park Güell"
                        },
                        new
                        {
                            Id = 17,
                            CityId = 9,
                            Description = "A biographical museum dedicated to Jewish wartime diarist Anne Frank.",
                            Name = "Anne Frank House"
                        },
                        new
                        {
                            Id = 18,
                            CityId = 9,
                            Description = "A Dutch national museum dedicated to arts and history.",
                            Name = "Rijksmuseum"
                        },
                        new
                        {
                            Id = 19,
                            CityId = 10,
                            Description = "An 18th-century neoclassical monument and symbol of the city.",
                            Name = "Brandenburg Gate"
                        },
                        new
                        {
                            Id = 20,
                            CityId = 10,
                            Description = "A memorial site commemorating the division of Berlin by the Berlin Wall.",
                            Name = "Berlin Wall Memorial"
                        },
                        new
                        {
                            Id = 21,
                            CityId = 11,
                            Description = "The principal public square of Venice.",
                            Name = "St. Mark's Square"
                        },
                        new
                        {
                            Id = 22,
                            CityId = 11,
                            Description = "A major water-traffic corridor in the city.",
                            Name = "Grand Canal"
                        },
                        new
                        {
                            Id = 23,
                            CityId = 12,
                            Description = "The tallest building in the world.",
                            Name = "Burj Khalifa"
                        },
                        new
                        {
                            Id = 24,
                            CityId = 12,
                            Description = "An artificial archipelago in the shape of a palm tree.",
                            Name = "Palm Jumeirah"
                        },
                        new
                        {
                            Id = 25,
                            CityId = 13,
                            Description = "A suspension bridge spanning the Golden Gate strait.",
                            Name = "Golden Gate Bridge"
                        },
                        new
                        {
                            Id = 26,
                            CityId = 13,
                            Description = "A small island with an abandoned federal prison.",
                            Name = "Alcatraz Island"
                        },
                        new
                        {
                            Id = 27,
                            CityId = 14,
                            Description = "A statue of Jesus Christ at the summit of Mount Corcovado.",
                            Name = "Christ the Redeemer"
                        },
                        new
                        {
                            Id = 28,
                            CityId = 14,
                            Description = "A famous beach known for its 4 km balneario.",
                            Name = "Copacabana Beach"
                        },
                        new
                        {
                            Id = 29,
                            CityId = 15,
                            Description = "The largest ancient castle in the world.",
                            Name = "Prague Castle"
                        },
                        new
                        {
                            Id = 30,
                            CityId = 15,
                            Description = "A historic bridge that crosses the Vltava river.",
                            Name = "Charles Bridge"
                        },
                        new
                        {
                            Id = 31,
                            CityId = 16,
                            Description = "A former Greek Orthodox Christian patriarchal cathedral, later an Ottoman imperial mosque.",
                            Name = "Hagia Sophia"
                        },
                        new
                        {
                            Id = 32,
                            CityId = 16,
                            Description = "One of the largest and oldest covered markets in the world.",
                            Name = "Grand Bazaar"
                        },
                        new
                        {
                            Id = 33,
                            CityId = 17,
                            Description = "A former imperial summer residence.",
                            Name = "Schönbrunn Palace"
                        },
                        new
                        {
                            Id = 34,
                            CityId = 17,
                            Description = "An opera house with a history dating back to the mid-19th century.",
                            Name = "Vienna State Opera"
                        },
                        new
                        {
                            Id = 35,
                            CityId = 18,
                            Description = "A complex of buildings at the heart of Bangkok.",
                            Name = "Grand Palace"
                        },
                        new
                        {
                            Id = 36,
                            CityId = 18,
                            Description = "A Buddhist temple on the Thonburi west bank of the Chao Phraya River.",
                            Name = "Wat Arun"
                        },
                        new
                        {
                            Id = 37,
                            CityId = 19,
                            Description = "A nature park spanning 101 hectares of reclaimed land.",
                            Name = "Gardens by the Bay"
                        },
                        new
                        {
                            Id = 38,
                            CityId = 19,
                            Description = "An integrated resort with a hotel, casino, retail mall, and convention centre.",
                            Name = "Marina Bay Sands"
                        },
                        new
                        {
                            Id = 39,
                            CityId = 20,
                            Description = "The highest hill on Hong Kong Island, offering panoramic views of the city.",
                            Name = "Victoria Peak"
                        },
                        new
                        {
                            Id = 40,
                            CityId = 20,
                            Description = "A theme park located on reclaimed land in Penny's Bay.",
                            Name = "Hong Kong Disneyland"
                        },
                        new
                        {
                            Id = 41,
                            CityId = 21,
                            Description = "The main royal palace of the Joseon dynasty.",
                            Name = "Gyeongbokgung Palace"
                        },
                        new
                        {
                            Id = 42,
                            CityId = 21,
                            Description = "A communication and observation tower on Namsan Mountain.",
                            Name = "N Seoul Tower"
                        },
                        new
                        {
                            Id = 43,
                            CityId = 22,
                            Description = "An ancient citadel located on a rocky outcrop above the city.",
                            Name = "Acropolis"
                        },
                        new
                        {
                            Id = 44,
                            CityId = 22,
                            Description = "A former temple dedicated to the goddess Athena.",
                            Name = "Parthenon"
                        },
                        new
                        {
                            Id = 45,
                            CityId = 23,
                            Description = "Ancient pyramid structures built as tombs for the country's pharaohs.",
                            Name = "Great Pyramids of Giza"
                        },
                        new
                        {
                            Id = 46,
                            CityId = 23,
                            Description = "A museum housing an extensive collection of ancient Egyptian antiquities.",
                            Name = "Egyptian Museum"
                        },
                        new
                        {
                            Id = 47,
                            CityId = 24,
                            Description = "A city square that separates the Kremlin from the historic merchant quarter.",
                            Name = "Red Square"
                        },
                        new
                        {
                            Id = 48,
                            CityId = 24,
                            Description = "A church in Red Square, featuring colorful onion domes.",
                            Name = "St. Basil's Cathedral"
                        },
                        new
                        {
                            Id = 49,
                            CityId = 25,
                            Description = "A 553.3 m-high concrete communications and observation tower.",
                            Name = "CN Tower"
                        },
                        new
                        {
                            Id = 50,
                            CityId = 25,
                            Description = "A museum of art, world culture and natural history.",
                            Name = "Royal Ontario Museum"
                        },
                        new
                        {
                            Id = 51,
                            CityId = 26,
                            Description = "An opera house considered one of the best in the world.",
                            Name = "Teatro Colón"
                        },
                        new
                        {
                            Id = 52,
                            CityId = 26,
                            Description = "A colorful neighborhood known for its vibrant houses and tango dancing.",
                            Name = "La Boca"
                        },
                        new
                        {
                            Id = 53,
                            CityId = 27,
                            Description = "A flat-topped mountain forming a prominent landmark overlooking the city.",
                            Name = "Table Mountain"
                        },
                        new
                        {
                            Id = 54,
                            CityId = 27,
                            Description = "An island where Nelson Mandela was imprisoned for 18 years.",
                            Name = "Robben Island"
                        },
                        new
                        {
                            Id = 55,
                            CityId = 28,
                            Description = "The old town of Stockholm, featuring medieval streets and architecture.",
                            Name = "Gamla Stan"
                        },
                        new
                        {
                            Id = 56,
                            CityId = 28,
                            Description = "A maritime museum displaying the only almost fully intact 17th-century ship.",
                            Name = "Vasa Museum"
                        },
                        new
                        {
                            Id = 57,
                            CityId = 29,
                            Description = "A botanical garden and artist's landscape garden.",
                            Name = "Jardin Majorelle"
                        },
                        new
                        {
                            Id = 58,
                            CityId = 29,
                            Description = "A famous square and market place in the medina quarter.",
                            Name = "Jemaa el-Fnaa"
                        },
                        new
                        {
                            Id = 59,
                            CityId = 30,
                            Description = "A Shinto shrine famous for its thousands of vermilion torii gates.",
                            Name = "Fushimi Inari Shrine"
                        },
                        new
                        {
                            Id = 60,
                            CityId = 30,
                            Description = "A Zen Buddhist temple known as the Golden Pavilion.",
                            Name = "Kinkaku-ji"
                        });
                });

            modelBuilder.Entity("CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
